# Generated by Django 3.2.5 on 2022-04-22 13:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220422_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 13, 4, 18, 645683, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 13, 4, 18, 645683, tzinfo=utc)),
        ),
    ]
