# Generated by Django 3.2.5 on 2022-04-22 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220422_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 13, 33, 28, 465614, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 22, 13, 33, 28, 465614, tzinfo=utc)),
        ),
    ]
